#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_split_3x5_3(KC_Q, KC_W, KC_E, KC_R, KC_T, KC_MUTE, KC_Y, KC_U, KC_I, KC_O, KC_P, LGUI_T(KC_A), LALT_T(KC_S), LCTL_T(KC_D), LSFT_T(KC_F), KC_G, KC_H, RSFT_T(KC_J), RCTL_T(KC_K), LALT_T(KC_L), RGUI_T(KC_QUOT), LT(9, KC_Z), RALT_T(KC_X), KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, RALT_T(KC_DOT), LT(9, KC_SLSH), LT(5, KC_ESC), LT(3, KC_SPC), LT(4, KC_TAB), TD(11), LT(6, KC_BSPC), LT(8, KC_DEL)),
	[1] = LAYOUT_split_3x5_3(KC_Q, KC_W, KC_F, KC_P, KC_G, KC_MUTE, KC_J, KC_L, KC_U, KC_Y, KC_QUOT, LGUI_T(KC_A), LALT_T(KC_R), LCTL_T(KC_S), LSFT_T(KC_T), KC_D, KC_H, RSFT_T(KC_N), RCTL_T(KC_E), LALT_T(KC_I), RGUI_T(KC_O), LT(9, KC_Z), RALT_T(KC_X), KC_C, KC_V, KC_B, KC_K, KC_M, KC_COMM, RALT_T(KC_DOT), LT(9, KC_SLSH), LT(5, KC_ESC), LT(3, KC_SPC), LT(4, KC_TAB), TD(11), LT(6, KC_BSPC), LT(8, KC_DEL)),
	[2] = LAYOUT_split_3x5_3(KC_Q, KC_W, KC_E, KC_R, KC_T, KC_MUTE, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_QUOT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_ESC, KC_SPC, KC_TAB, TD(12), KC_BSPC, KC_DEL),
	[3] = LAYOUT_split_3x5_3(TD(13), TD(2), TD(1), TD(0), QK_LAYER_LOCK, KC_MUTE, KC_INS, KC_HOME, KC_UP, KC_END, KC_PGUP, KC_LGUI, KC_LALT, KC_LCTL, KC_LSFT, KC_NO, TD(10), KC_LEFT, KC_DOWN, KC_RIGHT, KC_PGDN, KC_NO, KC_RALT, TD(6), TD(3), KC_NO, RCTL(KC_Y), RCTL(KC_V), RCTL(KC_C), RCTL(KC_X), RCTL(KC_Z), KC_NO, KC_NO, KC_NO, TD(12), KC_BSPC, KC_DEL),
	[4] = LAYOUT_split_3x5_3(TD(13), TD(2), TD(1), TD(0), QK_LAYER_LOCK, KC_MUTE, KC_NO, KC_WH_L, KC_MS_U, KC_WH_R, KC_WH_U, KC_LGUI, KC_LALT, KC_LCTL, KC_LSFT, KC_NO, KC_NO, KC_MS_L, KC_MS_D, KC_MS_R, KC_WH_D, KC_NO, KC_RALT, TD(7), TD(4), KC_NO, RCTL(KC_Y), RCTL(KC_V), RCTL(KC_C), RCTL(KC_X), RCTL(KC_Z), KC_NO, KC_NO, KC_NO, KC_BTN2, KC_BTN1, KC_BTN3),
	[5] = LAYOUT_split_3x5_3(TD(13), TD(2), TD(1), TD(0), QK_LAYER_LOCK, KC_MUTE, KC_NO, KC_NO, KC_VOLU, KC_NO, KC_NO, KC_LGUI, KC_LALT, KC_LCTL, KC_LSFT, KC_NO, KC_NO, KC_MPRV, KC_VOLD, KC_MNXT, KC_NO, KC_NO, KC_RALT, TD(8), TD(5), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_MSTP, KC_MPLY, KC_MUTE),
	[6] = LAYOUT_split_3x5_3(KC_LBRC, KC_7, KC_8, KC_9, KC_RBRC, KC_MUTE, QK_LAYER_LOCK, TD(0), TD(1), TD(2), TD(13), KC_SCLN, KC_4, KC_5, KC_6, KC_EQL, KC_NO, KC_RSFT, KC_RCTL, KC_LALT, KC_RGUI, KC_GRV, KC_1, KC_2, KC_3, KC_BSLS, KC_NO, TD(6), TD(3), KC_RALT, KC_NO, KC_DOT, KC_0, KC_MINS, KC_NO, KC_NO, KC_NO),
	[7] = LAYOUT_split_3x5_3(LSFT(KC_LBRC), LSFT(KC_7), LSFT(KC_8), LSFT(KC_9), LSFT(KC_RBRC), KC_MUTE, QK_LAYER_LOCK, TD(0), TD(1), TD(2), TD(13), LSFT(KC_SCLN), LSFT(KC_4), LSFT(KC_5), LSFT(KC_6), LSFT(KC_EQL), KC_NO, KC_RSFT, KC_RCTL, KC_LALT, KC_RGUI, LSFT(KC_GRV), LSFT(KC_1), LSFT(KC_2), LSFT(KC_3), LSFT(KC_BSLS), KC_NO, TD(7), TD(4), KC_RALT, KC_NO, LSFT(KC_9), LSFT(KC_0), LSFT(KC_MINS), KC_NO, KC_NO, KC_NO),
	[8] = LAYOUT_split_3x5_3(KC_F12, KC_F7, KC_F8, KC_F9, KC_PSCR, KC_MUTE, QK_LAYER_LOCK, TD(0), TD(1), TD(2), TD(13), KC_F11, KC_F4, KC_F5, KC_F6, KC_SCRL, KC_NO, KC_RSFT, KC_RCTL, KC_LALT, KC_RGUI, KC_F10, KC_F1, KC_F2, KC_F3, KC_PAUS, KC_NO, TD(8), TD(5), KC_RALT, KC_NO, KC_APP, KC_SPC, KC_TAB, KC_NO, KC_NO, KC_NO),
	[9] = LAYOUT_split_3x5_3(TD(13), TD(2), TD(1), TD(0), QK_LAYER_LOCK, KC_MUTE, QK_LAYER_LOCK, TD(0), TD(1), TD(2), TD(13), KC_LGUI, KC_LALT, KC_LCTL, KC_LSFT, KC_NO, KC_NO, KC_RSFT, KC_RCTL, KC_LALT, KC_RGUI, LCTL(KC_Z), LCTL(KC_X), LCTL(KC_C), LCTL(KC_V), LCTL(KC_Y), RCTL(KC_Y), RCTL(KC_V), RCTL(KC_C), RCTL(KC_X), RCTL(KC_Z), KC_BTN3, KC_BTN1, KC_BTN2, KC_BTN2, KC_BTN1, KC_BTN3)
};

const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][2] = {
    [0]  =  { ENCODER_CCW_CW(KC_VOLD, KC_VOLU) },
    [1]  =  { ENCODER_CCW_CW(KC_VOLD, KC_VOLU) },
    [2]  =  { ENCODER_CCW_CW(KC_VOLD, KC_VOLU) },
    [3]  =  { ENCODER_CCW_CW(KC_VOLD, KC_VOLU) },
    [4]  =  { ENCODER_CCW_CW(KC_VOLD, KC_VOLU) },
    [5]  =  { ENCODER_CCW_CW(KC_VOLD, KC_VOLU) },
    [6]  =  { ENCODER_CCW_CW(KC_VOLD, KC_VOLU) },
    [7]  =  { ENCODER_CCW_CW(KC_VOLD, KC_VOLU) },
    [8]  =  { ENCODER_CCW_CW(KC_VOLD, KC_VOLU) },
    [9]  =  { ENCODER_CCW_CW(KC_VOLD, KC_VOLU) }
};

bool get_custom_auto_shifted_key(uint16_t keycode, keyrecord_t *record) {
    if (IS_RETRO(keycode)) {
        return true;
    }
    return false;
}
